### ISSUE TITLE
BUG: 'Media.supported' is null or not an object  nonresponsive.min.js, line 4 character 16

### ISSUE THREAD

**Issue by christopherdarling** [weblinc/nonresponsive#1]
Downloaded the whole repo including media.match trying to run the test demo, but getting errors.

**Comment by knightdr** [comment]
Thanks for the report. My first thought is that you might be using v2 of MediaMatch.
Sorry for the hasty response but I'll have time to look at this later tonight/tomorrow morning. So in the mean time get v1 of MediaMatch which is a branch in the MediaMatch repo. Hope this helps. If you need this functionality right away, check out respond.js.

Thanks

**Comment by christopherdarling** [comment]
No problem. Thanks for taking the time to reply so quickly. Hopefully this script is updated to work with v2 of media.match soon.
I tried using Respond.js with media.match but they don't seem to play too nicely together :(

**Comment by knightdr** [comment]
The issue with respond.js and media.match is the test respond.js does at the beginning ("only all"). media.match supports this and allows all browsers including those that don't support it natively.

**Comment by christopherdarling** [comment]
Thanks. That's the problem, I'm using enquire.js which tests for "only all" support and exists if it doesn't exist. Your media.match polyfils that nicely. But my css media queries don't work without using something like Respond.js which exits if support for "only all" is found.

**Comment by knightdr** [comment]
@christopherdarling 
I've released a new version of this project. It still requires media-match to polyfill matchMedia.
I hope this works better for you, would love to here any feedback you may have.

Thanks

**Comment by christopherdarling** [comment]
@knightdr ahh fantastic, thanks for letting me know. I've got another responsive project coming up soon and I'll give this a try first.
